name: Application build

on:
  push:
    branches: 
      - main
      - 'v*.*.*'

  pull_request:
    branches:
      - main

jobs:

  rust-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cargo cache
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-$$ {{ hashFiles('**/Cargo.lock ')}}
          restore-keys: |
            $${{ runner.os }}-cargo-

      - name: Application tests
        run: cargo test --verbose

      - name: Application build
        run: cargo build --release
